data:
  batch_size: 1024
  train_dir: '/path/to/train/data'
  val_dir: '/path/to/val/data'
  train_events: 100000
  val_events: 100000
  pin_memory: true
  num_workers: 1
  persistent_workers: true

model:
  embedding_dim: 256
  dom_embed_dim: 128
  num_heads: 8
  hidden_size: 1024
  num_layers: 8
  mask_prob: 0.0

  directional:
    hidden_size: 1024

training:
  max_epochs: 60
  initial_lr: 1e-4
  max_lr: 7e-4
  weight_decay: 0.0
  amsgrad: false
  lr_scheduler: 'onecycle'
  pct_start: 0.01
  final_div_factor: 0.133333
  project: '2024-09-IceCube-finetuning'
  
  gpus: 1
  precision: "16-mixed"
  gradient_clip_val: 1.0
  val_check_interval: 1.0

  checkpoint:
    dirpath: 'checkpoints'
    save_top_k: 1
    monitor: 'val/loss'
    mode: 'min'
    save_last: true
    save_final: true

pretrained:
  model_type: 'flash'
  checkpoint_path: '/path/to/pretrained/model.pth'
  freeze_backbone: false
